// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv51AgCPtOZUCtJ16OyzpGMglIm4ec3GI',
    appId: '1:77229799225:web:238d35ceed7532eb065ae8',
    messagingSenderId: '77229799225',
    projectId: 'greener-61483',
    authDomain: 'greener-61483.firebaseapp.com',
    storageBucket: 'greener-61483.firebasestorage.app',
    measurementId: 'G-92EY9EEMQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKfSGFU5G6Q11hTMwO0YZnU1DLhzVhAc',
    appId: '1:77229799225:android:b79295cf1727ab46065ae8',
    messagingSenderId: '77229799225',
    projectId: 'greener-61483',
    storageBucket: 'greener-61483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDwyPI8v9ysGIv7AytuqOH_B64B6ztFU',
    appId: '1:77229799225:ios:556a638d7d2742a2065ae8',
    messagingSenderId: '77229799225',
    projectId: 'greener-61483',
    storageBucket: 'greener-61483.firebasestorage.app',
    iosClientId: '77229799225-aeofeg6n7261btl2c379nbpojgka1cgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.greener',
  );
}
